yarnPath: .yarn/releases/yarn-4.0.2.cjs

# npmScopes:
# 스코프 별 레지스트리 구성

# 레지스트리 별 구성
npmRegistries:
  "https://npm.pkg.github.com":
    # npm 레지스트리를 쿼리할 때 항상 인증 자격 증명을 보낼지 여부를 정의
    # - true이면 레지스트리에 요청을 보낼 때 항상 인증 자격 증명이 전송
    # - 비공개 npm 미러를 참조하도록 레지스트리를 구성한 경우가 아니라면 이 설정은 필요 없음
    npmAlwaysAuth: true

    # 레지스트리에 액세스할 때 기본적으로 사용할 인증 자격 증명을 정의
    # - 이전의 _auth 설정을 대체
    # - 구성에 암호화되지 않은 값을 저장해야 하므로 가능하면 npmAuthToken을 사용
    # npmAuthIdent: "username:password"

    # 레지스트리에 액세스할 때 기본적으로 사용할 인증 토큰을 정의
    # - 이전의 _authToken 설정을 대체
    # - npmScopes를 사용하여 여러 레지스트리를 정의하는 경우, npmRegistries 딕셔너리를 사용하면 레지스트리별로 이러한 자격 증명을 재정의 가능
    npmAuthToken: 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
